package maven.hibernate;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;

import org.hsqldb.util.DatabaseManagerSwing;

import maven.hibernate.conexao.FabricaJpaConexao;
import maven.hibernate.model.Contato;
import maven.hibernate.repository.ContatoJpaRepository;

public class ContatoApp {
	public static void main(String[] args) {
		//jpa();
		//jdbc();
		verBanco();
	}
	public static void verBanco() {
		//create table tab_contato (id integer generated by default as identity (start with 1), nome varchar(255), telefone varchar(255), primary key (id))
		//final String[] dbms = { "--user", "SA", "--url", "jdbc:hsqldb:file:/temp/db/sampledb" };
		//DatabaseManagerSwing.main(dbms);
		EntityManager em = FabricaJpaConexao.criarConexao();		
	}
	
	/*public static void jdbc() {
		
		ContatoJdbcRepository repository = new ContatoJdbcRepository();
		
		Contato contato = new Contato();
		contato.setNome("GLEYSON");
		contato.setTelefone("11 8798798798");
		
		repository.incluir(contato);
		
		contato = new Contato();
		contato.setNome("JEFERSON");
		contato.setTelefone("11 7678989669");
		
		repository.incluir(contato);
		
		repository.fechar();
		
	}
	
	public static void jpa() {
		
		ContatoJpaRepository repository = new ContatoJpaRepository();
		
		Contato contato = new Contato();
		contato.setNome("GLEYSON");
		contato.setTelefone("11 8798798798");
		
		repository.incluir(contato);
		
		contato = new Contato();
		contato.setNome("JEFERSON");
		contato.setTelefone("11 7678989669");
		
		repository.incluir(contato);
		
		List<Contato> contatos = repository.listar();
		
		
		for(Contato c: contatos) {
			System.out.println(c.getId() + " -- " + c.getNome());
		}
	}*/
	
}
